
CONNECT admin_qldh/admin_qldh@localhost:1521/XE;
alter session set "_ORACLE_SCRIPT"=true;
-- tạo bảng
CREATE TABLE DONVI (
    MADV VARCHAR2(10) PRIMARY KEY,
    TENDV VARCHAR2(100) NOT NULL,
    LOAIDV VARCHAR2(10) CHECK (LOAIDV IN ('Khoa', 'Phòng')),
    TRGDV VARCHAR2(10)
);

CREATE TABLE NHANVIEN (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    PHAI VARCHAR2(3) CHECK (PHAI IN ('Nam', 'Nữ')),
    NGSINH DATE,
    LUONG NUMBER(10,2),
    PHUCAP NUMBER(10,2),
    DT VARCHAR2(15),
    VAITRO VARCHAR2(50),
    MADV VARCHAR2(10),
    CONSTRAINT FK_NHANVIEN_DONVI FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);

ALTER TABLE DONVI ADD CONSTRAINT FK_DONVI_NHANVIEN FOREIGN KEY (TRGDV) REFERENCES NHANVIEN(MANV);

CREATE TABLE SINHVIEN (
    MASV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    PHAI VARCHAR2(3) CHECK (PHAI IN ('Nam', 'Nữ')),
    NGSINH DATE,
    DCHI VARCHAR2(200),
    DT VARCHAR2(15),
    KHOA VARCHAR2(10),
    TINHTRANG VARCHAR2(20) CHECK (TINHTRANG IN ('Đang học', 'Nghỉ học', 'Bảo lưu')),
    CONSTRAINT FK_SINHVIEN_DONVI FOREIGN KEY (KHOA) REFERENCES DONVI(MADV)
);

CREATE TABLE HOCPHAN (
    MAHP VARCHAR2(10) PRIMARY KEY,
    TENHP VARCHAR2(100) NOT NULL,
    SOTC NUMBER(2),
    STLT NUMBER(3),
    STTH NUMBER(3),
    MADV VARCHAR2(10),
    CONSTRAINT FK_HOCPHAN_DONVI FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);

CREATE TABLE MOMON (
    MAMM VARCHAR2(10) PRIMARY KEY,
    MAHP VARCHAR2(10),
    MAGV VARCHAR2(10),
    HK NUMBER(1) CHECK (HK IN (1, 2, 3)),
    NAM NUMBER(4),
    CONSTRAINT FK_MOMON_HOCPHAN FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP),
    CONSTRAINT FK_MOMON_NHANVIEN FOREIGN KEY (MAGV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE DANGKY (
    MASV VARCHAR2(10),
    MAMM VARCHAR2(10),
    DIEMTH NUMBER(4,2),
    DIEMQT NUMBER(4,2),
    DIEMCK NUMBER(4,2),
    DIEMTK NUMBER(4,2),
    CONSTRAINT PK_DANGKY PRIMARY KEY (MASV, MAMM),
    CONSTRAINT FK_DANGKY_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    CONSTRAINT FK_DANGKY_MOMON FOREIGN KEY (MAMM) REFERENCES MOMON(MAMM)
);
-- test_view1
CREATE OR REPLACE VIEW test_view_1 AS
SELECT nv.MANV, nv.HOTEN, nv.PHAI, nv.NGSINH, nv.LUONG, nv.PHUCAP, nv.DT,
       nv.VAITRO, dv.TENDV as DON_VI, dv.LOAIDV as LOAI_DON_VI
FROM NHANVIEN nv
JOIN DONVI dv ON nv.MADV = dv.MADV;

--test_view_2
CREATE OR REPLACE VIEW test_view_2 AS
SELECT sv.MASV, sv.HOTEN, sv.PHAI, sv.NGSINH, sv.DCHI, sv.DT,
       dv.TENDV as KHOA_HOC, sv.TINHTRANG
FROM SINHVIEN sv
JOIN DONVI dv ON sv.KHOA = dv.MADV;
--tạo user

CREATE USER nv001 IDENTIFIED BY nv001;
CREATE USER nv002 IDENTIFIED BY nv002;
CREATE USER nv003 IDENTIFIED BY nv003;
CREATE USER nv004 IDENTIFIED BY nv004;
CREATE USER nv005 IDENTIFIED BY nv005;

CREATE USER sv001 IDENTIFIED BY sv001;
CREATE USER sv002 IDENTIFIED BY sv002;
CREATE USER sv003 IDENTIFIED BY nv003;
CREATE USER sv004 IDENTIFIED BY nv004;
CREATE USER sv005 IDENTIFIED BY nv005;
--tạo role
CREATE ROLE GV_ROLE;
CREATE ROLE NV_ROLE;
CREATE ROLE TP_ROLE;
CREATE ROLE SV_ROLE;