CREATE PLUGGABLE DATABASE QLDH
  ADMIN USER admin_qldh IDENTIFIED BY admin_qldh
  FILE_NAME_CONVERT = ('D:\ORACLE\ORADATA\XE\PDBSEED\', 'D:\ORACLE\ORADATA\XE\QLDH\');
  
ALTER PLUGGABLE DATABASE QLDH OPEN;
--SHOW CON_NAME;
--SHOW USER;

ALTER SESSION SET CONTAINER = QLDH;
GRANT CONNECT, RESOURCE TO admin_qldh;
GRANT CREATE SESSION TO admin_qldh;
GRANT ALTER SYSTEM TO admin_qldh;
GRANT dba to admin_qldh;

GRANT CREATE USER TO ADMIN_QLDH;
GRANT DROP USER TO ADMIN_QLDH;
GRANT CONNECT TO ADMIN_QLDH WITH ADMIN OPTION;
GRANT ALTER USER TO ADMIN_QLDH;
GRANT CREATE ROLE TO ADMIN_QLDH;
GRANT GRANT ANY ROLE TO ADMIN_QLDH;
