CREATE PLUGGABLE DATABASE QLDH
ADMIN USER adminqldh IDENTIFIED BY adminqldh
FILE_NAME_CONVERT = ('D:\ORACLE\ORADATA\XE\PDBSEED\', 'D:\ORACLE\ORADATA\XE\QLDH\'); 
ALTER PLUGGABLE DATABASE QLDH OPEN;
--SHOW CON_NAME;
--SHOW USER;
ALTER SESSION SET CONTAINER = QLDH;
GRANT CONNECT, RESOURCE TO adminqldh;
GRANT CREATE SESSION TO adminqldh;
GRANT ALTER SYSTEM TO adminqldh;
GRANT dba to adminqldh;

GRANT CREATE USER TO adminqldh;
GRANT DROP USER TO adminqldh;
GRANT CONNECT TO ADMINQLDH WITH ADMIN OPTION;
GRANT ALTER USER TO ADMINQLDH;
GRANT CREATE ROLE TO ADMINQLDH;
GRANT GRANT ANY ROLE TO ADMINQLDH;
